-- MySQL Script generated by MySQL Workbench
-- Thu Mar 28 17:35:18 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sgcitas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sgcitas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sgcitas` DEFAULT CHARACTER SET utf8mb4 ;
USE `sgcitas` ;

-- -----------------------------------------------------
-- Table `sgcitas`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgcitas`.`roles` (
  `Id_Rol` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre_Rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_Rol`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sgcitas`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgcitas`.`usuarios` (
  `Id_Usuarios` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre_Usuarios` VARCHAR(45) NOT NULL,
  `Apellido_Usuarios` VARCHAR(45) NOT NULL,
  `Correo_Usuarios` VARCHAR(45) NOT NULL,
  `Telefono_Usuarios` VARCHAR(45) NOT NULL,
  `Contraseña_Usuarios` VARCHAR(45) NOT NULL,
  `Id_Rol` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Id_Usuarios`),
  INDEX `FK_Id_Rol` (`Id_Rol` ASC) ,
  CONSTRAINT `FK_Id_Rol`
    FOREIGN KEY (`Id_Rol`)
    REFERENCES `sgcitas`.`roles` (`Id_Rol`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sgcitas`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgcitas`.`clientes` (
  `Id_Clientes` INT(11) NOT NULL AUTO_INCREMENT,
  `activo` TINYINT(1) NULL DEFAULT 1,
  `Id_Usuarios` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Id_Clientes`),
  INDEX `Fk_Id_Usuarios` (`Id_Usuarios` ASC) ,
  CONSTRAINT `Fk_Id_Usuarios`
    FOREIGN KEY (`Id_Usuarios`)
    REFERENCES `sgcitas`.`usuarios` (`Id_Usuarios`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sgcitas`.`estilistas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgcitas`.`estilistas` (
  `Id_Estilistas` INT(11) NOT NULL AUTO_INCREMENT,
  `activo` TINYINT(1) NULL DEFAULT 1,
  `Id_Usuarios` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Id_Estilistas`),
  INDEX `Fk_2Id_Usuarios` (`Id_Usuarios` ASC) ,
  CONSTRAINT `Fk_2Id_Usuarios`
    FOREIGN KEY (`Id_Usuarios`)
    REFERENCES `sgcitas`.`usuarios` (`Id_Usuarios`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sgcitas`.`servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgcitas`.`servicios` (
  `Id_Servicios` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre_Servicios` VARCHAR(45) NOT NULL,
  `Valor_Servicios` DECIMAL(12,2) NOT NULL,
  `Descripcion_Servicios` VARCHAR(200) NULL DEFAULT NULL,
  `Imagen_Servicios` MEDIUMBLOB NOT NULL,
  PRIMARY KEY (`Id_Servicios`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sgcitas`.`citas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgcitas`.`citas` (
  `Id_Citas` INT(11) NOT NULL AUTO_INCREMENT,
  `start` DATETIME NOT NULL,
  `end` DATETIME NOT NULL,
  `Id_Clientes` INT(11) NULL DEFAULT NULL,
  `Id_Estilistas` INT(11) NULL DEFAULT NULL,
  `Id_Servicios` INT(11) NULL DEFAULT NULL,
  `activo` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`Id_Citas`),
  INDEX `FK1_Id_Clientes` (`Id_Clientes` ASC) ,
  INDEX `FK2_Id_Estilistas` (`Id_Estilistas` ASC) ,
  INDEX `FK3_Id_Servicios` (`Id_Servicios` ASC) ,
  CONSTRAINT `FK1_Id_Clientes`
    FOREIGN KEY (`Id_Clientes`)
    REFERENCES `sgcitas`.`clientes` (`Id_Clientes`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK2_Id_Estilistas`
    FOREIGN KEY (`Id_Estilistas`)
    REFERENCES `sgcitas`.`estilistas` (`Id_Estilistas`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK3_Id_Servicios`
    FOREIGN KEY (`Id_Servicios`)
    REFERENCES `sgcitas`.`servicios` (`Id_Servicios`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sgcitas`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgcitas`.`productos` (
  `Id_Productos` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre_Productos` VARCHAR(45) NOT NULL,
  `Precio_Productos` DECIMAL(12,2) NOT NULL,
  `Cantidad_Productos` INT(11) NOT NULL,
  `Descripcion_Productos` VARCHAR(200) NULL DEFAULT NULL,
  `Imagen_Productos` MEDIUMBLOB NOT NULL,
  `Id_Clientes` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Id_Productos`),
  INDEX `Fk_Id_Clientes` (`Id_Clientes` ASC) ,
  CONSTRAINT `Fk_Id_Clientes`
    FOREIGN KEY (`Id_Clientes`)
    REFERENCES `sgcitas`.`clientes` (`Id_Clientes`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sgcitas`.`facturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgcitas`.`facturas` (
  `Id_Facturas` INT(11) NOT NULL AUTO_INCREMENT,
  `Fecha_Factura` DATETIME NOT NULL,
  `Precio_Total_Productos` INT(11) NOT NULL,
  `Precio_Total_Servicios` INT(11) NOT NULL,
  `Factura_Total` DECIMAL(12,2) NOT NULL,
  `Cantidad_Productos` INT(11) NULL DEFAULT NULL,
  `Cantidad_Servicios` INT(11) NULL DEFAULT NULL,
  `Id_Productos` INT(11) NULL DEFAULT NULL,
  `Id_Servicios` INT(11) NULL DEFAULT NULL,
  `Id_Clientes` INT(11) NULL DEFAULT NULL,
  `Id_Estilistas` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Id_Facturas`),
  INDEX `FK1_Id_Productos` (`Id_Productos` ASC) ,
  INDEX `FK2_Id_Servicios` (`Id_Servicios` ASC) ,
  INDEX `FK3_Id_Clientes` (`Id_Clientes` ASC) ,
  INDEX `FK4_Id_Estilistas` (`Id_Estilistas` ASC) ,
  CONSTRAINT `FK1_Id_Productos`
    FOREIGN KEY (`Id_Productos`)
    REFERENCES `sgcitas`.`productos` (`Id_Productos`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK2_Id_Servicios`
    FOREIGN KEY (`Id_Servicios`)
    REFERENCES `sgcitas`.`servicios` (`Id_Servicios`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK3_Id_Clientes`
    FOREIGN KEY (`Id_Clientes`)
    REFERENCES `sgcitas`.`clientes` (`Id_Clientes`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK4_Id_Estilistas`
    FOREIGN KEY (`Id_Estilistas`)
    REFERENCES `sgcitas`.`estilistas` (`Id_Estilistas`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sgcitas`.`comisiones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgcitas`.`comisiones` (
  `Id_Comisiones` INT(11) NOT NULL AUTO_INCREMENT,
  `Pagar_Comisiones` DECIMAL(12,2) NOT NULL,
  `Estado_De_Pago_Comisiones` TINYINT(4) NOT NULL,
  `Id_Facturas` INT(11) NULL DEFAULT NULL,
  `Id_Estilistas` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Id_Comisiones`),
  INDEX `Fk1_Id_Facturas` (`Id_Facturas` ASC) ,
  INDEX `Fk5_Id_Estilistas` (`Id_Estilistas` ASC) ,
  CONSTRAINT `Fk1_Id_Facturas`
    FOREIGN KEY (`Id_Facturas`)
    REFERENCES `sgcitas`.`facturas` (`Id_Facturas`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Fk5_Id_Estilistas`
    FOREIGN KEY (`Id_Estilistas`)
    REFERENCES `sgcitas`.`estilistas` (`Id_Estilistas`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
